# Generated by Django 5.0.6 on 2024-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='fullname_reg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
