# Generated by Django 5.0.6 on 2024-08-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0002_alter_register_fullname_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='fullname_reg',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
