# Generated by Django 5.0.6 on 2024-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0003_alter_register_fullname_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='gender_reg',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='image_reg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
