# Generated by Django 5.0.6 on 2024-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0004_register_gender_reg_register_image_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image_reg',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\harshil c pogram\\website\\django\\clg_HealthCare\\images_user'),
        ),
    ]
