# Generated by Django 5.0.6 on 2024-08-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0007_alter_register_image_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image_reg',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='user_profileimg/'),
        ),
    ]
