# Generated by Django 5.0.6 on 2024-09-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0008_alter_register_image_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ImageField(blank=True, max_length=250, null=True, upload_to='user_report/')),
            ],
        ),
    ]
