# Generated by Django 5.0.6 on 2024-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0009_user_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_report',
        ),
        migrations.AddField(
            model_name='register',
            name='report',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='user_report/'),
        ),
    ]
