# Generated by Django 5.0.6 on 2024-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0010_delete_user_report_register_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='report',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='user_report/'),
        ),
    ]
