# Generated by Django 5.0.6 on 2024-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0011_alter_register_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('doctor_qualification', models.CharField(blank=True, max_length=255)),
                ('doctor_experience', models.CharField(blank=True, max_length=2)),
                ('doctor_contact', models.CharField(blank=True, max_length=10)),
                ('doctor_email', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
