# Generated by Django 5.0.6 on 2024-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0016_alter_doctor_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines_name', models.CharField(blank=True, max_length=255)),
                ('medicines_description', models.CharField(blank=True, max_length=255)),
                ('medicines_price', models.CharField(blank=True, max_length=255)),
                ('medicines_image', models.ImageField(blank=True, max_length=250, null=True, upload_to='medicines_image/')),
            ],
        ),
    ]
