# Generated by Django 5.0.6 on 2024-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0017_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=255, null=True)),
                ('app_age', models.CharField(max_length=3)),
                ('app_gender', models.CharField(blank=True, max_length=6, null=True)),
                ('app_phono', models.CharField(max_length=10, unique=True)),
                ('app_email', models.EmailField(max_length=255)),
                ('app_address', models.CharField(max_length=700, null=True)),
                ('app_illness', models.CharField(max_length=1000, null=True)),
                ('app_dateandtime', models.DateTimeField()),
            ],
        ),
    ]
