# Generated by Django 5.0.6 on 2024-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0019_appointment_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_phono',
            field=models.CharField(max_length=10),
        ),
    ]
