# Generated by Django 5.0.6 on 2024-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0020_alter_appointment_app_phono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
