# Generated by Django 5.0.6 on 2024-09-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0021_remove_appointment_app_status_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='app_status',
        ),
    ]
