# Generated by Django 5.0.6 on 2024-09-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0022_rename_status_appointment_app_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordermedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=255)),
                ('customername', models.CharField(blank=True, max_length=255)),
                ('medicinename', models.CharField(blank=True, max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
